// ReactJS/src/components/Todo/TodoHeader/index.jsx
import React from 'react';
// import PropTypes from 'prop-types';

const propTypes = {};
const defaultProps = {};

class TodoHeader extends React.Component {
  render() {
    return (
      <header className="header">
        <h1>todos</h1>
        <input className="new-todo" type="text" placeholder="What needs to be done?" />
        <input className="toggle-all" id="toggle-all" type="checkbox" />
        <label style={{ top: '15px' }} htmlFor="toggle-all">Mark all async complete</label>
      </header>
    );
  }
}

TodoHeader.propTypes = propTypes;
TodoHeader.defaultProps = defaultProps;

export default TodoHeader;

// vue-vuex/src/components/TodoHeader.vue
<template>
  <header class="header">
    <h1>todos</h1>
    <input
      class="new-todo"
      type="text"
      v-model.trim="value"
      @keydown.enter="addProcess"
      placeholder="What needs to be done?"
    />
  </header>
</template>
<script>
export default {
  data() {
    return {
      value: '',
    };
  },
  methods: {
    addProcess() {
      this.addTodo(this.value);
      this.value = '';
    },
  },
  props: {
    addTodo: Function,
  },
};
</script>
