// vue-vuex/src/components/TodoFooter.vue
<template>
  <footer class="footer">
    <span class="todo-count"><strong>{{ length }}</strong> item left</span>
    <ul class="filters">
      <li><a href="#/" :class="{ selected: filter === 'all' }">All</a></li>
      <li><a href="#/active" :class="{ selected: filter === 'active' }" >Active</a></li>
      <li><a href="#/completed" :class="{ selected: filter === 'completed' }">Completed</a></li>
    </ul>
    <button class="clear-completed" @click="deleteCompleted">
      Clear completed
    </button>
  </footer>
</template>
<script>
export default {
  name: 'todo-footer',
  props: {
    filter: String,
    length: Number,
    deleteCompleted: Function,
  },
};
</script>

// ReactJS/src/components/Todo/TodoFooter/index.jsx
import React from 'react';
// import PropTypes from 'prop-types';

const propTypes = {};
const defaultProps = {};

class TodoFooter extends React.Component {
  render() {
    return (
      <footer className="footer" style={{ display: 'block' }}>
        <span className="todo-count"><strong>1</strong> item left</span>
        <ul className="filters">
          <li><a href="#/" className="selected">All</a></li>
          <li><a href="#/active">Active</a></li>
          <li><a href="#/completed">Completed</a></li>
        </ul>
        <button className="clear-completed" style={{ display: 'block' }}>
          Clear completed
        </button>
      </footer>
    );
  }
}

TodoFooter.propTypes = propTypes;
TodoFooter.defaultProps = defaultProps;

export default TodoFooter;
